### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by kfox1111** [common-workflow-language/cwl-v1.2#92]
Is there a part of the specification that allows steps to be annotated with something like "tags" that allows specific runners to be targeted ala gitlab ci / gitlab-runners?

We have various clusters available to us. K8s, HPC, cloud, instruments, etc, etc.
Curious if there is a way to create one workflow that could have different steps that run across those clusters. Does the spec allow for this? Are there any implementations that do too?

**Comment by tetron** [comment]
Hi @kfox1111, welcome!

This particular issue tracker is intended for the text of the specification itself rather than general CWL questions.  You'll get more visibility and discussion if you post questions like this to the CWL forum: https://cwl.discourse.group/

That said, the spec doesn't have anything to say about tags or targets, but allows custom hints that can change the behavior of an implementation.  Arvados supports a custom ClusterTarget hint that is sort of like what you are looking for:

https://doc.arvados.org/v2.1/user/cwl/federated-workflows.html

**Comment by kfox1111** [comment]
Ok. Thanks for the info. :)
